---
title: "Um Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)

respostas = read_csv(here::here("data/enade-ccc-2017.csv"),
                     col_types = "cccdccdddc")
regioes = 
cursos = respostas %>% 
    group_by(UF) %>% 
    summarise(n = n(), 
              media = mean(media))

criterios = respostas %>% 
    group_by(UF, categoria) %>%
    summarise(media = mean(media))

```

Column {data-width=650}
-----------------------------------------------------------------------

### Parte 1

## Aqui poderia analisar qual a média de diversidade por região.

```{r}
regioes = bind_rows(
    tibble(
        regiao = "norte",
        estado = c("AM", "RR", "AP", "PA", "TO", "RO", "AC")
    ),
    tibble(
        regiao = "sul",
        estado = c("RS", "SC", "PR")
    ),
    tibble(
        regiao = "sudeste",
        estado = c("ES", "MG", "SP", "RJ")
    ),
    tibble(
        regiao = "centroeste",
        estado = c("GO", "DF", "MT", "MS")
    ),
    tibble(
        regiao = "nordeste",
        estado = c("BA", "MA", "PI", "PB", "AL", "PE", "RN", "SE", "CE")
    )
)

respostas = respostas %>% 
    left_join(regioes, by = c("UF" = "estado"))

criterios %>%
    filter(categoria != "Outros") %>%
    ggplot(aes(
        x = reorder(UF, media),
        y = reorder(categoria, media),
        fill = media
    )) +
    geom_tile() + 
    scale_fill_viridis() + 
    theme(legend.position = "bottom")

medias = respostas %>%
    filter(tema == "Diversidade") %>%
    group_by(regiao) %>%
    summarise(media = mean(media))

p = respostas %>%
    filter(tema == "Diversidade") %>%
    ggplot(aes(
        x = regiao,
        y = media
    )) +
    geom_point() +
    geom_point(
        data = medias,
        color = "orange",
        shape = 15,
        size = 3
    )

ggplotly(p)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Parte 2
## Aqui poderia analisar a média de conteúdo útil pra prática
```{r}
cursos %>% 
    ggplot(aes(x = UF, y = media)) + 
    geom_col() + 
    coord_flip()

medias_cont = respostas %>%
    filter(tema == "Conteúdo útil p/ prática") %>%
    group_by(regiao) %>%
    summarise(media = mean(media))

p = respostas %>%
    filter(tema == "Conteúdo útil p/ prática") %>%
    ggplot(aes(
        x = regiao,
        y = media
    )) +
    geom_point() +
    geom_point(
        data = medias_cont,
        color = "orange",
        shape = 15,
        size = 3
    )

ggplotly(p)


```

### Parte 3
## Aqui a média por UF de pensamento crítico

```{r}
cursos %>% 
    ggplot(aes(x = UF, y = n)) + 
    geom_col()

medias_pens = respostas %>%
    filter(tema =="Pensamento crítico") %>%
    group_by(UF) %>%
    summarise(media = mean(media))

p = respostas %>%
    filter(tema == "Pensamento crítico") %>%
    ggplot(aes(
        x = UF,
        y = media
    )) +
    geom_point() +
    geom_point(
        data = medias_pens,
        color = "orange",
        shape = 15,
        size = 3
    )

ggplotly(p)

```

